package com.example.kotlinexamples

class Pokedex {
    companion object {
        fun getPokedex(): List<Pokemon> {
            val pokedex = mutableListOf<Pokemon>()
            pokedex.add(Pokemon("Bulbasaur", "Grass - Poison"))
            pokedex.add(Pokemon("Ivysaur", "Grass - Poison"))
            pokedex.add(Pokemon("Venusaur", "Grass - Poison"))
            pokedex.add(Pokemon("Charmander", "Fire"))
            pokedex.add(Pokemon("Charmeleon", "Fire"))
            pokedex.add(Pokemon("Charizard", "Fire - Flying"))
            pokedex.add(Pokemon("Squirtle", "Water"))
            pokedex.add(Pokemon("Wartortle", "Water"))
            pokedex.add(Pokemon("Blastoise", "Water"))
            pokedex.add(Pokemon("Caterpie", "Bug"))
            pokedex.add(Pokemon("Metapod", "Bug"))
            pokedex.add(Pokemon("Butterfree", "Bug - Flying"))
            pokedex.add(Pokemon("Weedle", "Bug - Poison"))
            pokedex.add(Pokemon("Kakuna", "Bug - Poison"))
            pokedex.add(Pokemon("Beedrill", "Bug - Poison"))
            pokedex.add(Pokemon("Pidgey", "Normal - Flying"))
            pokedex.add(Pokemon("Pidgeotto", "Normal - Flying"))
            pokedex.add(Pokemon("Pidgeot", "Normal - Flying"))
            pokedex.add(Pokemon("Rattata", "Normal"))
            pokedex.add(Pokemon("Raticate", "Normal"))
            pokedex.add(Pokemon("Spearow", "Normal - Flying"))
            pokedex.add(Pokemon("Fearow", "Normal - Flying"))
            pokedex.add(Pokemon("Ekans", "Poison"))
            pokedex.add(Pokemon("Arbok", "Poison"))
            pokedex.add(Pokemon("Pikachu", "Electric"))
            pokedex.add(Pokemon("Raichu", "Electric"))
            pokedex.add(Pokemon("Sandshrew", "Ground"))
            pokedex.add(Pokemon("Sandslash", "Ground"))
            pokedex.add(Pokemon("Nidoran♀", "Poison"))
            pokedex.add(Pokemon("Nidorina", "Poison"))
            pokedex.add(Pokemon("Nidoqueen", "Poison - Ground"))
            pokedex.add(Pokemon("Nidoran♂", "Poison"))
            pokedex.add(Pokemon("Nidorino", "Poison"))
            pokedex.add(Pokemon("Nidoking", "Poison - Ground"))
            pokedex.add(Pokemon("Clefairy", "Fairy"))
            pokedex.add(Pokemon("Clefable", "Fairy"))
            pokedex.add(Pokemon("Vulpix", "Fire"))
            pokedex.add(Pokemon("Ninetales", "Fire"))
            pokedex.add(Pokemon("Jigglypuff", "Normal - Fairy"))
            pokedex.add(Pokemon("Wigglytuff", "Normal - Fairy"))
            pokedex.add(Pokemon("Zubat", "Poison - Flying"))
            pokedex.add(Pokemon("Golbat", "Poison - Flying"))
            pokedex.add(Pokemon("Oddish", "Grass - Poison"))
            pokedex.add(Pokemon("Gloom", "Grass - Poison"))
            pokedex.add(Pokemon("Vileplume", "Grass - Poison"))
            pokedex.add(Pokemon("Paras", "Bug - Grass"))
            pokedex.add(Pokemon("Parasect", "Bug - Grass"))
            pokedex.add(Pokemon("Venonat", "Bug - Poison"))
            pokedex.add(Pokemon("Venomoth", "Bug - Poison"))
            pokedex.add(Pokemon("Diglett", "Ground"))
            pokedex.add(Pokemon("Dugtrio", "Ground"))
            pokedex.add(Pokemon("Meowth", "Normal"))
            pokedex.add(Pokemon("Persian", "Normal"))
            pokedex.add(Pokemon("Psyduck", "Water"))
            pokedex.add(Pokemon("Golduck", "Water"))
            pokedex.add(Pokemon("Mankey", "Fighting"))
            pokedex.add(Pokemon("Primeape", "Fighting"))
            pokedex.add(Pokemon("Growlithe", "Fire"))
            pokedex.add(Pokemon("Arcanine", "Fire"))
            pokedex.add(Pokemon("Poliwag", "Water"))
            pokedex.add(Pokemon("Poliwhirl", "Water"))
            pokedex.add(Pokemon("Poliwrath", "Water - Fighting"))
            pokedex.add(Pokemon("Abra", "Psychic"))
            pokedex.add(Pokemon("Kadabra", "Psychic"))
            pokedex.add(Pokemon("Alakazam", "Psychic"))
            pokedex.add(Pokemon("Machop", "Fighting"))
            pokedex.add(Pokemon("Machoke", "Fighting"))
            pokedex.add(Pokemon("Machamp", "Fighting"))
            pokedex.add(Pokemon("Bellsprout", "Grass - Poison"))
            pokedex.add(Pokemon("Weepinbell", "Grass - Poison"))
            pokedex.add(Pokemon("Victreebel", "Grass - Poison"))
            pokedex.add(Pokemon("Tentacool", "Water - Poison"))
            pokedex.add(Pokemon("Tentacruel", "Water - Poison"))
            pokedex.add(Pokemon("Geodude", "Rock - Ground"))
            pokedex.add(Pokemon("Graveler", "Rock - Ground"))
            pokedex.add(Pokemon("Golem", "Rock - Ground"))
            pokedex.add(Pokemon("Ponyta", "Fire"))
            pokedex.add(Pokemon("Rapidash", "Fire"))
            pokedex.add(Pokemon("Slowpoke", "Water - Psychic"))
            pokedex.add(Pokemon("Slowbro", "Water - Psychic"))
            pokedex.add(Pokemon("Magnemite", "Electric - Steel"))
            pokedex.add(Pokemon("Magneton", "Electric - Steel"))
            pokedex.add(Pokemon("Farfetch'd", "Normal - Flying"))
            pokedex.add(Pokemon("Doduo", "Normal - Flying"))
            pokedex.add(Pokemon("Dodrio", "Normal - Flying"))
            pokedex.add(Pokemon("Seel", "Water"))
            pokedex.add(Pokemon("Dewgong", "Water - Ice"))
            pokedex.add(Pokemon("Grimer", "Poison"))
            pokedex.add(Pokemon("Muk", "Poison"))
            pokedex.add(Pokemon("Shellder", "Water"))
            pokedex.add(Pokemon("Cloyster", "Water - Ice"))
            pokedex.add(Pokemon("Gastly", "Ghost - Poison"))
            pokedex.add(Pokemon("Haunter", "Ghost - Poison"))
            pokedex.add(Pokemon("Gengar", "Ghost - Poison"))
            pokedex.add(Pokemon("Onix", "Rock - Ground"))
            pokedex.add(Pokemon("Drowzee", "Psychic"))
            pokedex.add(Pokemon("Hypno", "Psychic"))
            pokedex.add(Pokemon("Krabby", "Water"))
            pokedex.add(Pokemon("Kingler", "Water"))
            pokedex.add(Pokemon("Voltorb", "Electric"))
            pokedex.add(Pokemon("Electrode", "Electric"))
            pokedex.add(Pokemon("Exeggcute", "Grass - Psychic"))
            pokedex.add(Pokemon("Exeggutor", "Grass - Psychic"))
            pokedex.add(Pokemon("Cubone", "Ground"))
            pokedex.add(Pokemon("Marowak", "Ground"))
            pokedex.add(Pokemon("Hitmonlee", "Fighting"))
            pokedex.add(Pokemon("Hitmonchan", "Fighting"))
            pokedex.add(Pokemon("Lickitung", "Normal"))
            pokedex.add(Pokemon("Koffing", "Poison"))
            pokedex.add(Pokemon("Weezing", "Poison"))
            pokedex.add(Pokemon("Rhyhorn", "Ground - Rock"))
            pokedex.add(Pokemon("Rhydon", "Ground - Rock"))
            pokedex.add(Pokemon("Chansey", "Normal"))
            pokedex.add(Pokemon("Tangela", "Grass"))
            pokedex.add(Pokemon("Kangaskhan", "Normal"))
            pokedex.add(Pokemon("Horsea", "Water"))
            pokedex.add(Pokemon("Seadra", "Water"))
            pokedex.add(Pokemon("Goldeen", "Water"))
            pokedex.add(Pokemon("Seaking", "Water"))
            pokedex.add(Pokemon("Staryu", "Water"))
            pokedex.add(Pokemon("Starmie", "Water - Psychic"))
            pokedex.add(Pokemon("Mr. Mime", "Psychic - Fairy"))
            pokedex.add(Pokemon("Scyther", "Bug - Flying"))
            pokedex.add(Pokemon("Jynx", "Ice - Psychic"))
            pokedex.add(Pokemon("Electabuzz", "Electric"))
            pokedex.add(Pokemon("Magmar", "Fire"))
            pokedex.add(Pokemon("Pinsir", "Bug"))
            pokedex.add(Pokemon("Tauros", "Normal"))
            pokedex.add(Pokemon("Magikarp", "Water"))
            pokedex.add(Pokemon("Gyarados", "Water - Flying"))
            pokedex.add(Pokemon("Lapras", "Water - Ice"))
            pokedex.add(Pokemon("Ditto", "Normal"))
            pokedex.add(Pokemon("Eevee", "Normal"))
            pokedex.add(Pokemon("Vaporeon", "Water"))
            pokedex.add(Pokemon("Jolteon", "Electric"))
            pokedex.add(Pokemon("Flareon", "Fire"))
            pokedex.add(Pokemon("Porygon", "Normal"))
            pokedex.add(Pokemon("Omanyte", "Rock - Water"))
            pokedex.add(Pokemon("Omastar", "Rock - Water"))
            pokedex.add(Pokemon("Kabuto", "Rock - Water"))
            pokedex.add(Pokemon("Kabutops", "Rock - Water"))
            pokedex.add(Pokemon("Aerodactyl", "Rock - Flying"))
            pokedex.add(Pokemon("Snorlax", "Normal"))
            pokedex.add(Pokemon("Articuno", "Ice - Flying"))
            pokedex.add(Pokemon("Zapdos", "Electric - Flying"))
            pokedex.add(Pokemon("Moltres", "Fire - Flying"))
            pokedex.add(Pokemon("Dratini", "Dragon"))
            pokedex.add(Pokemon("Dragonair", "Dragon"))
            pokedex.add(Pokemon("Dragonite", "Dragon - Flying"))
            pokedex.add(Pokemon("Mewtwo", "Psychic"))
            pokedex.add(Pokemon("Mew", "Psychic"))
            pokedex.add(Pokemon("Chikorita", "Grass"))
            pokedex.add(Pokemon("Bayleef", "Grass"))
            pokedex.add(Pokemon("Meganium", "Grass"))
            pokedex.add(Pokemon("Cyndaquil", "Fire"))
            pokedex.add(Pokemon("Quilava", "Fire"))
            pokedex.add(Pokemon("Typhlosion", "Fire"))
            pokedex.add(Pokemon("Totodile", "Water"))
            pokedex.add(Pokemon("Croconaw", "Water"))
            pokedex.add(Pokemon("Feraligatr", "Water"))
            pokedex.add(Pokemon("Sentret", "Normal"))
            pokedex.add(Pokemon("Furret", "Normal"))
            pokedex.add(Pokemon("Hoothoot", "Normal - Flying"))
            pokedex.add(Pokemon("Noctowl", "Normal - Flying"))
            pokedex.add(Pokemon("Ledyba", "Bug - Flying"))
            pokedex.add(Pokemon("Ledian", "Bug - Flying"))
            pokedex.add(Pokemon("Spinarak", "Bug - Poison"))
            pokedex.add(Pokemon("Ariados", "Bug - Poison"))
            pokedex.add(Pokemon("Crobat", "Poison - Flying"))
            pokedex.add(Pokemon("Chinchou", "Water - Electric"))
            pokedex.add(Pokemon("Lanturn", "Water - Electric"))
            pokedex.add(Pokemon("Pichu", "Electric"))
            pokedex.add(Pokemon("Cleffa", "Fairy"))
            pokedex.add(Pokemon("Igglybuff", "Normal - Fairy"))
            pokedex.add(Pokemon("Togepi", "Fairy"))
            pokedex.add(Pokemon("Togetic", "Fairy - Flying"))
            pokedex.add(Pokemon("Natu", "Psychic - Flying"))
            pokedex.add(Pokemon("Xatu", "Psychic - Flying"))
            pokedex.add(Pokemon("Mareep", "Electric"))
            pokedex.add(Pokemon("Flaaffy", "Electric"))
            pokedex.add(Pokemon("Ampharos", "Electric"))
            pokedex.add(Pokemon("Bellossom", "Grass"))
            pokedex.add(Pokemon("Marill", "Water - Fairy"))
            pokedex.add(Pokemon("Azumarill", "Water - Fairy"))
            pokedex.add(Pokemon("Sudowoodo", "Rock"))
            pokedex.add(Pokemon("Politoed", "Water"))
            pokedex.add(Pokemon("Hoppip", "Grass - Flying"))
            pokedex.add(Pokemon("Skiploom", "Grass - Flying"))
            pokedex.add(Pokemon("Jumpluff", "Grass - Flying"))
            pokedex.add(Pokemon("Aipom", "Normal"))
            pokedex.add(Pokemon("Sunkern", "Grass"))
            pokedex.add(Pokemon("Sunflora", "Grass"))
            pokedex.add(Pokemon("Yanma", "Bug - Flying"))
            pokedex.add(Pokemon("Wooper", "Water - Ground"))
            pokedex.add(Pokemon("Quagsire", "Water - Ground"))
            pokedex.add(Pokemon("Espeon", "Psychic"))
            pokedex.add(Pokemon("Umbreon", "Dark"))
            pokedex.add(Pokemon("Murkrow", "Dark - Flying"))
            pokedex.add(Pokemon("Slowking", "Water - Psychic"))
            pokedex.add(Pokemon("Misdreavus", "Ghost"))
            pokedex.add(Pokemon("Unown", "Psychic"))
            pokedex.add(Pokemon("Wobbuffet", "Psychic"))
            pokedex.add(Pokemon("Girafarig", "Normal - Psychic"))
            pokedex.add(Pokemon("Pineco", "Bug"))
            pokedex.add(Pokemon("Forretress", "Bug - Steel"))
            pokedex.add(Pokemon("Dunsparce", "Normal"))
            pokedex.add(Pokemon("Gligar", "Ground - Flying"))
            pokedex.add(Pokemon("Steelix", "Steel - Ground"))
            pokedex.add(Pokemon("Snubbull", "Fairy"))
            pokedex.add(Pokemon("Granbull", "Fairy"))
            pokedex.add(Pokemon("Qwilfish", "Water - Poison"))
            pokedex.add(Pokemon("Scizor", "Bug - Steel"))
            pokedex.add(Pokemon("Shuckle", "Bug - Rock"))
            pokedex.add(Pokemon("Heracross", "Bug - Fighting"))
            pokedex.add(Pokemon("Sneasel", "Dark - Ice"))
            pokedex.add(Pokemon("Teddiursa", "Normal"))
            pokedex.add(Pokemon("Ursaring", "Normal"))
            pokedex.add(Pokemon("Slugma", "Fire"))
            pokedex.add(Pokemon("Magcargo", "Fire - Rock"))
            pokedex.add(Pokemon("Swinub", "Ice - Ground"))
            pokedex.add(Pokemon("Piloswine", "Ice - Ground"))
            pokedex.add(Pokemon("Corsola", "Water - Rock"))
            pokedex.add(Pokemon("Remoraid", "Water"))
            pokedex.add(Pokemon("Octillery", "Water"))
            pokedex.add(Pokemon("Delibird", "Ice - Flying"))
            pokedex.add(Pokemon("Mantine", "Water - Flying"))
            pokedex.add(Pokemon("Skarmory", "Steel - Flying"))
            pokedex.add(Pokemon("Houndour", "Dark - Fire"))
            pokedex.add(Pokemon("Houndoom", "Dark - Fire"))
            pokedex.add(Pokemon("Kingdra", "Water - Dragon"))
            pokedex.add(Pokemon("Phanpy", "Ground"))
            pokedex.add(Pokemon("Donphan", "Ground"))
            pokedex.add(Pokemon("Porygon2", "Normal"))
            pokedex.add(Pokemon("Stantler", "Normal"))
            pokedex.add(Pokemon("Smeargle", "Normal"))
            pokedex.add(Pokemon("Tyrogue", "Fighting"))
            pokedex.add(Pokemon("Hitmontop", "Fighting"))
            pokedex.add(Pokemon("Smoochum", "Ice - Psychic"))
            pokedex.add(Pokemon("Elekid", "Electric"))
            pokedex.add(Pokemon("Magby", "Fire"))
            pokedex.add(Pokemon("Miltank", "Normal"))
            pokedex.add(Pokemon("Blissey", "Normal"))
            pokedex.add(Pokemon("Raikou", "Electric"))
            pokedex.add(Pokemon("Entei", "Fire"))
            pokedex.add(Pokemon("Suicune", "Water"))
            pokedex.add(Pokemon("Larvitar", "Rock - Ground"))
            pokedex.add(Pokemon("Pupitar", "Rock - Ground"))
            pokedex.add(Pokemon("Tyranitar", "Rock - Dark"))
            pokedex.add(Pokemon("Lugia", "Psychic - Flying"))
            pokedex.add(Pokemon("Ho-oh", "Fire - Flying"))
            pokedex.add(Pokemon("Celebi", "Psychic - Grass"))
            pokedex.add(Pokemon("Treecko", "Grass"))
            pokedex.add(Pokemon("Grovyle", "Grass"))
            pokedex.add(Pokemon("Sceptile", "Grass"))
            pokedex.add(Pokemon("Torchic", "Fire"))
            pokedex.add(Pokemon("Combusken", "Fire - Fighting"))
            pokedex.add(Pokemon("Blaziken", "Fire - Fighting"))
            pokedex.add(Pokemon("Mudkip", "Water"))
            pokedex.add(Pokemon("Marshtomp", "Water - Ground"))
            pokedex.add(Pokemon("Swampert", "Water - Ground"))
            pokedex.add(Pokemon("Poochyena", "Dark"))
            pokedex.add(Pokemon("Mightyena", "Dark"))
            pokedex.add(Pokemon("Zigzagoon", "Normal"))
            pokedex.add(Pokemon("Linoone", "Normal"))
            pokedex.add(Pokemon("Wurmple", "Bug"))
            pokedex.add(Pokemon("Silcoon", "Bug"))
            pokedex.add(Pokemon("Beautifly", "Bug - Flying"))
            pokedex.add(Pokemon("Cascoon", "Bug"))
            pokedex.add(Pokemon("Dustox", "Bug - Poison"))
            pokedex.add(Pokemon("Lotad", "Water - Grass"))
            pokedex.add(Pokemon("Lombre", "Water - Grass"))
            pokedex.add(Pokemon("Ludicolo", "Water - Grass"))
            pokedex.add(Pokemon("Seedot", "Grass"))
            pokedex.add(Pokemon("Nuzleaf", "Grass - Dark"))
            pokedex.add(Pokemon("Shiftry", "Grass - Dark"))
            pokedex.add(Pokemon("Taillow", "Normal - Flying"))
            pokedex.add(Pokemon("Swellow", "Normal - Flying"))
            pokedex.add(Pokemon("Wingull", "Water - Flying"))
            pokedex.add(Pokemon("Pelipper", "Water - Flying"))
            pokedex.add(Pokemon("Ralts", "Psychic - Fairy"))
            pokedex.add(Pokemon("Kirlia", "Psychic - Fairy"))
            pokedex.add(Pokemon("Gardevoir", "Psychic - Fairy"))
            pokedex.add(Pokemon("Surskit", "Bug - Water"))
            pokedex.add(Pokemon("Masquerain", "Bug - Flying"))
            pokedex.add(Pokemon("Shroomish", "Grass"))
            pokedex.add(Pokemon("Breloom", "Grass - Fighting"))
            pokedex.add(Pokemon("Slakoth", "Normal"))
            pokedex.add(Pokemon("Vigoroth", "Normal"))
            pokedex.add(Pokemon("Slaking", "Normal"))
            pokedex.add(Pokemon("Nincada", "Bug - Ground"))
            pokedex.add(Pokemon("Ninjask", "Bug - Flying"))
            pokedex.add(Pokemon("Shedinja", "Bug - Ghost"))
            pokedex.add(Pokemon("Whismur", "Normal"))
            pokedex.add(Pokemon("Loudred", "Normal"))
            pokedex.add(Pokemon("Exploud", "Normal"))
            pokedex.add(Pokemon("Makuhita", "Fighting"))
            pokedex.add(Pokemon("Hariyama", "Fighting"))
            pokedex.add(Pokemon("Azurill", "Normal - Fairy"))
            pokedex.add(Pokemon("Nosepass", "Rock"))
            pokedex.add(Pokemon("Skitty", "Normal"))
            pokedex.add(Pokemon("Delcatty", "Normal"))
            pokedex.add(Pokemon("Sableye", "Dark - Ghost"))
            pokedex.add(Pokemon("Mawile", "Steel - Fairy"))
            pokedex.add(Pokemon("Aron", "Steel - Rock"))
            pokedex.add(Pokemon("Lairon", "Steel - Rock"))
            pokedex.add(Pokemon("Aggron", "Steel - Rock"))
            pokedex.add(Pokemon("Meditite", "Fighting - Psychic"))
            pokedex.add(Pokemon("Medicham", "Fighting - Psychic"))
            pokedex.add(Pokemon("Electrike", "Electric"))
            pokedex.add(Pokemon("Manectric", "Electric"))
            pokedex.add(Pokemon("Plusle", "Electric"))
            pokedex.add(Pokemon("Minun", "Electric"))
            pokedex.add(Pokemon("Volbeat", "Bug"))
            pokedex.add(Pokemon("Illumise", "Bug"))
            pokedex.add(Pokemon("Roselia", "Grass - Poison"))
            pokedex.add(Pokemon("Gulpin", "Poison"))
            pokedex.add(Pokemon("Swalot", "Poison"))
            pokedex.add(Pokemon("Carvanha", "Water - Dark"))
            pokedex.add(Pokemon("Sharpedo", "Water - Dark"))
            pokedex.add(Pokemon("Wailmer", "Water"))
            pokedex.add(Pokemon("Wailord", "Water"))
            pokedex.add(Pokemon("Numel", "Fire - Ground"))
            pokedex.add(Pokemon("Camerupt", "Fire - Ground"))
            pokedex.add(Pokemon("Torkoal", "Fire"))
            pokedex.add(Pokemon("Spoink", "Psychic"))
            pokedex.add(Pokemon("Grumpig", "Psychic"))
            pokedex.add(Pokemon("Spinda", "Normal"))
            pokedex.add(Pokemon("Trapinch", "Ground"))
            pokedex.add(Pokemon("Vibrava", "Ground - Dragon"))
            pokedex.add(Pokemon("Flygon", "Ground - Dragon"))
            pokedex.add(Pokemon("Cacnea", "Grass"))
            pokedex.add(Pokemon("Cacturne", "Grass - Dark"))
            pokedex.add(Pokemon("Swablu", "Normal - Flying"))
            pokedex.add(Pokemon("Altaria", "Dragon - Flying"))
            pokedex.add(Pokemon("Zangoose", "Normal"))
            pokedex.add(Pokemon("Seviper", "Poison"))
            pokedex.add(Pokemon("Lunatone", "Rock - Psychic"))
            pokedex.add(Pokemon("Solrock", "Rock - Psychic"))
            pokedex.add(Pokemon("Barboach", "Water - Ground"))
            pokedex.add(Pokemon("Whiscash", "Water - Ground"))
            pokedex.add(Pokemon("Corphish", "Water"))
            pokedex.add(Pokemon("Crawdaunt", "Water - Dark"))
            pokedex.add(Pokemon("Baltoy", "Ground - Psychic"))
            pokedex.add(Pokemon("Claydol", "Ground - Psychic"))
            pokedex.add(Pokemon("Lileep", "Rock - Grass"))
            pokedex.add(Pokemon("Cradily", "Rock - Grass"))
            pokedex.add(Pokemon("Anorith", "Rock - Bug"))
            pokedex.add(Pokemon("Armaldo", "Rock - Bug"))
            pokedex.add(Pokemon("Feebas", "Water"))
            pokedex.add(Pokemon("Milotic", "Water"))
            pokedex.add(Pokemon("Castform", "Normal"))
            pokedex.add(Pokemon("Kecleon", "Normal"))
            pokedex.add(Pokemon("Shuppet", "Ghost"))
            pokedex.add(Pokemon("Banette", "Ghost"))
            pokedex.add(Pokemon("Duskull", "Ghost"))
            pokedex.add(Pokemon("Dusclops", "Ghost"))
            pokedex.add(Pokemon("Tropius", "Grass - Flying"))
            pokedex.add(Pokemon("Chimecho", "Psychic"))
            pokedex.add(Pokemon("Absol", "Dark"))
            pokedex.add(Pokemon("Wynaut", "Psychic"))
            pokedex.add(Pokemon("Snorunt", "Ice"))
            pokedex.add(Pokemon("Glalie", "Ice"))
            pokedex.add(Pokemon("Spheal", "Ice - Water"))
            pokedex.add(Pokemon("Sealeo", "Ice - Water"))
            pokedex.add(Pokemon("Walrein", "Ice - Water"))
            pokedex.add(Pokemon("Clamperl", "Water"))
            pokedex.add(Pokemon("Huntail", "Water"))
            pokedex.add(Pokemon("Gorebyss", "Water"))
            pokedex.add(Pokemon("Relicanth", "Water - Rock"))
            pokedex.add(Pokemon("Luvdisc", "Water"))
            pokedex.add(Pokemon("Bagon", "Dragon"))
            pokedex.add(Pokemon("Shelgon", "Dragon"))
            pokedex.add(Pokemon("Salamence", "Dragon - Flying"))
            pokedex.add(Pokemon("Beldum", "Steel - Psychic"))
            pokedex.add(Pokemon("Metang", "Steel - Psychic"))
            pokedex.add(Pokemon("Metagross", "Steel - Psychic"))
            pokedex.add(Pokemon("Regirock", "Rock"))
            pokedex.add(Pokemon("Regice", "Ice"))
            pokedex.add(Pokemon("Registeel", "Steel"))
            pokedex.add(Pokemon("Latias", "Dragon - Psychic"))
            pokedex.add(Pokemon("Latios", "Dragon - Psychic"))
            pokedex.add(Pokemon("Kyogre", "Water"))
            pokedex.add(Pokemon("Groudon", "Ground"))
            pokedex.add(Pokemon("Rayquaza", "Dragon - Flying"))
            pokedex.add(Pokemon("Jirachi", "Steel - Psychic"))
            pokedex.add(Pokemon("Deoxys", "Psychic"))
            pokedex.add(Pokemon("Turtwig", "Grass"))
            pokedex.add(Pokemon("Grotle", "Grass"))
            pokedex.add(Pokemon("Torterra", "Grass - Ground"))
            pokedex.add(Pokemon("Chimchar", "Fire"))
            pokedex.add(Pokemon("Monferno", "Fire - Fighting"))
            pokedex.add(Pokemon("Infernape", "Fire - Fighting"))
            pokedex.add(Pokemon("Piplup", "Water"))
            pokedex.add(Pokemon("Prinplup", "Water"))
            pokedex.add(Pokemon("Empoleon", "Water - Steel"))
            pokedex.add(Pokemon("Starly", "Normal - Flying"))
            pokedex.add(Pokemon("Staravia", "Normal - Flying"))
            pokedex.add(Pokemon("Staraptor", "Normal - Flying"))
            pokedex.add(Pokemon("Bidoof", "Normal"))
            pokedex.add(Pokemon("Bibarel", "Normal - Water"))
            pokedex.add(Pokemon("Kricketot", "Bug"))
            pokedex.add(Pokemon("Kricketune", "Bug"))
            pokedex.add(Pokemon("Shinx", "Electric"))
            pokedex.add(Pokemon("Luxio", "Electric"))
            pokedex.add(Pokemon("Luxray", "Electric"))
            pokedex.add(Pokemon("Budew", "Grass - Poison"))
            pokedex.add(Pokemon("Roserade", "Grass - Poison"))
            pokedex.add(Pokemon("Cranidos", "Rock"))
            pokedex.add(Pokemon("Rampardos", "Rock"))
            pokedex.add(Pokemon("Shieldon", "Rock - Steel"))
            pokedex.add(Pokemon("Bastiodon", "Rock - Steel"))
            pokedex.add(Pokemon("Burmy", "Bug"))
            pokedex.add(Pokemon("Wormadam", "Bug - Grass"))
            pokedex.add(Pokemon("Mothim", "Bug - Flying"))
            pokedex.add(Pokemon("Combee", "Bug - Flying"))
            pokedex.add(Pokemon("Vespiquen", "Bug - Flying"))
            pokedex.add(Pokemon("Pachirisu", "Electric"))
            pokedex.add(Pokemon("Buizel", "Water"))
            pokedex.add(Pokemon("Floatzel", "Water"))
            pokedex.add(Pokemon("Cherubi", "Grass"))
            pokedex.add(Pokemon("Cherrim", "Grass"))
            pokedex.add(Pokemon("Shellos", "Water"))
            pokedex.add(Pokemon("Gastrodon", "Water - Ground"))
            pokedex.add(Pokemon("Ambipom", "Normal"))
            pokedex.add(Pokemon("Drifloon", "Ghost - Flying"))
            pokedex.add(Pokemon("Drifblim", "Ghost - Flying"))
            pokedex.add(Pokemon("Buneary", "Normal"))
            pokedex.add(Pokemon("Lopunny", "Normal"))
            pokedex.add(Pokemon("Mismagius", "Ghost"))
            pokedex.add(Pokemon("Honchkrow", "Dark - Flying"))
            pokedex.add(Pokemon("Glameow", "Normal"))
            pokedex.add(Pokemon("Purugly", "Normal"))
            pokedex.add(Pokemon("Chingling", "Psychic"))
            pokedex.add(Pokemon("Stunky", "Poison - Dark"))
            pokedex.add(Pokemon("Skuntank", "Poison - Dark"))
            pokedex.add(Pokemon("Bronzor", "Steel - Psychic"))
            pokedex.add(Pokemon("Bronzong", "Steel - Psychic"))
            pokedex.add(Pokemon("Bonsly", "Rock"))
            pokedex.add(Pokemon("Mime Jr.", "Psychic - Fairy"))
            pokedex.add(Pokemon("Happiny", "Normal"))
            pokedex.add(Pokemon("Chatot", "Normal - Flying"))
            pokedex.add(Pokemon("Spiritomb", "Ghost - Dark"))
            pokedex.add(Pokemon("Gible", "Dragon - Ground"))
            pokedex.add(Pokemon("Gabite", "Dragon - Ground"))
            pokedex.add(Pokemon("Garchomp", "Dragon - Ground"))
            pokedex.add(Pokemon("Munchlax", "Normal"))
            pokedex.add(Pokemon("Riolu", "Fighting"))
            pokedex.add(Pokemon("Lucario", "Fighting - Steel"))
            pokedex.add(Pokemon("Hippopotas", "Ground"))
            pokedex.add(Pokemon("Hippowdon", "Ground"))
            pokedex.add(Pokemon("Skorupi", "Poison - Bug"))
            pokedex.add(Pokemon("Drapion", "Poison - Dark"))
            pokedex.add(Pokemon("Croagunk", "Poison - Fighting"))
            pokedex.add(Pokemon("Toxicroak", "Poison - Fighting"))
            pokedex.add(Pokemon("Carnivine", "Grass"))
            pokedex.add(Pokemon("Finneon", "Water"))
            pokedex.add(Pokemon("Lumineon", "Water"))
            pokedex.add(Pokemon("Mantyke", "Water - Flying"))
            pokedex.add(Pokemon("Snover", "Grass - Ice"))
            pokedex.add(Pokemon("Abomasnow", "Grass - Ice"))
            pokedex.add(Pokemon("Weavile", "Dark - Ice"))
            pokedex.add(Pokemon("Magnezone", "Electric - Steel"))
            pokedex.add(Pokemon("Lickilicky", "Normal"))
            pokedex.add(Pokemon("Rhyperior", "Ground - Rock"))
            pokedex.add(Pokemon("Tangrowth", "Grass"))
            pokedex.add(Pokemon("Electivire", "Electric"))
            pokedex.add(Pokemon("Magmortar", "Fire"))
            pokedex.add(Pokemon("Togekiss", "Fairy - Flying"))
            pokedex.add(Pokemon("Yanmega", "Bug - Flying"))
            pokedex.add(Pokemon("Leafeon", "Grass"))
            pokedex.add(Pokemon("Glaceon", "Ice"))
            pokedex.add(Pokemon("Gliscor", "Ground - Flying"))
            pokedex.add(Pokemon("Mamoswine", "Ice - Ground"))
            pokedex.add(Pokemon("Porygon-Z", "Normal"))
            pokedex.add(Pokemon("Gallade", "Psychic - Fighting"))
            pokedex.add(Pokemon("Probopass", "Rock - Steel"))
            pokedex.add(Pokemon("Dusknoir", "Ghost"))
            pokedex.add(Pokemon("Froslass", "Ice - Ghost"))
            pokedex.add(Pokemon("Rotom", "Electric - Ghost"))
            pokedex.add(Pokemon("Uxie", "Psychic"))
            pokedex.add(Pokemon("Mesprit", "Psychic"))
            pokedex.add(Pokemon("Azelf", "Psychic"))
            pokedex.add(Pokemon("Dialga", "Steel - Dragon"))
            pokedex.add(Pokemon("Palkia", "Water - Dragon"))
            pokedex.add(Pokemon("Heatran", "Fire - Steel"))
            pokedex.add(Pokemon("Regigigas", "Normal"))
            pokedex.add(Pokemon("Giratina", "Ghost - Dragon"))
            pokedex.add(Pokemon("Cresselia", "Psychic"))
            pokedex.add(Pokemon("Phione", "Water"))
            pokedex.add(Pokemon("Manaphy", "Water"))
            pokedex.add(Pokemon("Darkrai", "Dark"))
            pokedex.add(Pokemon("Shaymin", "Grass"))
            pokedex.add(Pokemon("Arceus", "Normal"))
            pokedex.add(Pokemon("Victini", "Psychic - Fire"))
            pokedex.add(Pokemon("Snivy", "Grass"))
            pokedex.add(Pokemon("Servine", "Grass"))
            pokedex.add(Pokemon("Serperior", "Grass"))
            pokedex.add(Pokemon("Tepig", "Fire"))
            pokedex.add(Pokemon("Pignite", "Fire - Fighting"))
            pokedex.add(Pokemon("Emboar", "Fire - Fighting"))
            pokedex.add(Pokemon("Oshawott", "Water"))
            pokedex.add(Pokemon("Dewott", "Water"))
            pokedex.add(Pokemon("Samurott", "Water"))
            pokedex.add(Pokemon("Patrat", "Normal"))
            pokedex.add(Pokemon("Watchog", "Normal"))
            pokedex.add(Pokemon("Lillipup", "Normal"))
            pokedex.add(Pokemon("Herdier", "Normal"))
            pokedex.add(Pokemon("Stoutland", "Normal"))
            pokedex.add(Pokemon("Purrloin", "Dark"))
            pokedex.add(Pokemon("Liepard", "Dark"))
            pokedex.add(Pokemon("Pansage", "Grass"))
            pokedex.add(Pokemon("Simisage", "Grass"))
            pokedex.add(Pokemon("Pansear", "Fire"))
            pokedex.add(Pokemon("Simisear", "Fire"))
            pokedex.add(Pokemon("Panpour", "Water"))
            pokedex.add(Pokemon("Simipour", "Water"))
            pokedex.add(Pokemon("Munna", "Psychic"))
            pokedex.add(Pokemon("Musharna", "Psychic"))
            pokedex.add(Pokemon("Pidove", "Normal - Flying"))
            pokedex.add(Pokemon("Tranquill", "Normal - Flying"))
            pokedex.add(Pokemon("Unfezant", "Normal - Flying"))
            pokedex.add(Pokemon("Blitzle", "Electric"))
            pokedex.add(Pokemon("Zebstrika", "Electric"))
            pokedex.add(Pokemon("Roggenrola", "Rock"))
            pokedex.add(Pokemon("Boldore", "Rock"))
            pokedex.add(Pokemon("Gigalith", "Rock"))
            pokedex.add(Pokemon("Woobat", "Psychic - Flying"))
            pokedex.add(Pokemon("Swoobat", "Psychic - Flying"))
            pokedex.add(Pokemon("Drilbur", "Ground"))
            pokedex.add(Pokemon("Excadrill", "Ground - Steel"))
            pokedex.add(Pokemon("Audino", "Normal"))
            pokedex.add(Pokemon("Timburr", "Fighting"))
            pokedex.add(Pokemon("Gurdurr", "Fighting"))
            pokedex.add(Pokemon("Conkeldurr", "Fighting"))
            pokedex.add(Pokemon("Tympole", "Water"))
            pokedex.add(Pokemon("Palpitoad", "Water - Ground"))
            pokedex.add(Pokemon("Seismitoad", "Water - Ground"))
            pokedex.add(Pokemon("Throh", "Fighting"))
            pokedex.add(Pokemon("Sawk", "Fighting"))
            pokedex.add(Pokemon("Sewaddle", "Bug - Grass"))
            pokedex.add(Pokemon("Swadloon", "Bug - Grass"))
            pokedex.add(Pokemon("Leavanny", "Bug - Grass"))
            pokedex.add(Pokemon("Venipede", "Bug - Poison"))
            pokedex.add(Pokemon("Whirlipede", "Bug - Poison"))
            pokedex.add(Pokemon("Scolipede", "Bug - Poison"))
            pokedex.add(Pokemon("Cottonee", "Grass - Fairy"))
            pokedex.add(Pokemon("Whimsicott", "Grass - Fairy"))
            pokedex.add(Pokemon("Petilil", "Grass"))
            pokedex.add(Pokemon("Lilligant", "Grass"))
            pokedex.add(Pokemon("Basculin", "Water"))
            pokedex.add(Pokemon("Sandile", "Ground - Dark"))
            pokedex.add(Pokemon("Krokorok", "Ground - Dark"))
            pokedex.add(Pokemon("Krookodile", "Ground - Dark"))
            pokedex.add(Pokemon("Darumaka", "Fire"))
            pokedex.add(Pokemon("Darmanitan", "Fire"))
            pokedex.add(Pokemon("Maractus", "Grass"))
            pokedex.add(Pokemon("Dwebble", "Bug - Rock"))
            pokedex.add(Pokemon("Crustle", "Bug - Rock"))
            pokedex.add(Pokemon("Scraggy", "Dark - Fighting"))
            pokedex.add(Pokemon("Scrafty", "Dark - Fighting"))
            pokedex.add(Pokemon("Sigilyph", "Psychic - Flying"))
            pokedex.add(Pokemon("Yamask", "Ghost"))
            pokedex.add(Pokemon("Cofagrigus", "Ghost"))
            pokedex.add(Pokemon("Tirtouga", "Water - Rock"))
            pokedex.add(Pokemon("Carracosta", "Water - Rock"))
            pokedex.add(Pokemon("Archen", "Rock - Flying"))
            pokedex.add(Pokemon("Archeops", "Rock - Flying"))
            pokedex.add(Pokemon("Trubbish", "Poison"))
            pokedex.add(Pokemon("Garbodor", "Poison"))
            pokedex.add(Pokemon("Zorua", "Dark"))
            pokedex.add(Pokemon("Zoroark", "Dark"))
            pokedex.add(Pokemon("Minccino", "Normal"))
            pokedex.add(Pokemon("Cinccino", "Normal"))
            pokedex.add(Pokemon("Gothita", "Psychic"))
            pokedex.add(Pokemon("Gothorita", "Psychic"))
            pokedex.add(Pokemon("Gothitelle", "Psychic"))
            pokedex.add(Pokemon("Solosis", "Psychic"))
            pokedex.add(Pokemon("Duosion", "Psychic"))
            pokedex.add(Pokemon("Reuniclus", "Psychic"))
            pokedex.add(Pokemon("Ducklett", "Water - Flying"))
            pokedex.add(Pokemon("Swanna", "Water - Flying"))
            pokedex.add(Pokemon("Vanillite", "Ice"))
            pokedex.add(Pokemon("Vanillish", "Ice"))
            pokedex.add(Pokemon("Vanilluxe", "Ice"))
            pokedex.add(Pokemon("Deerling", "Normal - Grass"))
            pokedex.add(Pokemon("Sawsbuck", "Normal - Grass"))
            pokedex.add(Pokemon("Emolga", "Electric - Flying"))
            pokedex.add(Pokemon("Karrablast", "Bug"))
            pokedex.add(Pokemon("Escavalier", "Bug - Steel"))
            pokedex.add(Pokemon("Foongus", "Grass - Poison"))
            pokedex.add(Pokemon("Amoonguss", "Grass - Poison"))
            pokedex.add(Pokemon("Frillish", "Water - Ghost"))
            pokedex.add(Pokemon("Jellicent", "Water - Ghost"))
            pokedex.add(Pokemon("Alomomola", "Water"))
            pokedex.add(Pokemon("Joltik", "Bug - Electric"))
            pokedex.add(Pokemon("Galvantula", "Bug - Electric"))
            pokedex.add(Pokemon("Ferroseed", "Grass - Steel"))
            pokedex.add(Pokemon("Ferrothorn", "Grass - Steel"))
            pokedex.add(Pokemon("Klink", "Steel"))
            pokedex.add(Pokemon("Klang", "Steel"))
            pokedex.add(Pokemon("Klinklang", "Steel"))
            pokedex.add(Pokemon("Tynamo", "Electric"))
            pokedex.add(Pokemon("Eelektrik", "Electric"))
            pokedex.add(Pokemon("Eelektross", "Electric"))
            pokedex.add(Pokemon("Elgyem", "Psychic"))
            pokedex.add(Pokemon("Beheeyem", "Psychic"))
            pokedex.add(Pokemon("Litwick", "Ghost - Fire"))
            pokedex.add(Pokemon("Lampent", "Ghost - Fire"))
            pokedex.add(Pokemon("Chandelure", "Ghost - Fire"))
            pokedex.add(Pokemon("Axew", "Dragon"))
            pokedex.add(Pokemon("Fraxure", "Dragon"))
            pokedex.add(Pokemon("Haxorus", "Dragon"))
            pokedex.add(Pokemon("Cubchoo", "Ice"))
            pokedex.add(Pokemon("Beartic", "Ice"))
            pokedex.add(Pokemon("Cryogonal", "Ice"))
            pokedex.add(Pokemon("Shelmet", "Bug"))
            pokedex.add(Pokemon("Accelgor", "Bug"))
            pokedex.add(Pokemon("Stunfisk", "Ground - Electric"))
            pokedex.add(Pokemon("Mienfoo", "Fighting"))
            pokedex.add(Pokemon("Mienshao", "Fighting"))
            pokedex.add(Pokemon("Druddigon", "Dragon"))
            pokedex.add(Pokemon("Golett", "Ground - Ghost"))
            pokedex.add(Pokemon("Golurk", "Ground - Ghost"))
            pokedex.add(Pokemon("Pawniard", "Dark - Steel"))
            pokedex.add(Pokemon("Bisharp", "Dark - Steel"))
            pokedex.add(Pokemon("Bouffalant", "Normal"))
            pokedex.add(Pokemon("Rufflet", "Normal - Flying"))
            pokedex.add(Pokemon("Braviary", "Normal - Flying"))
            pokedex.add(Pokemon("Vullaby", "Dark - Flying"))
            pokedex.add(Pokemon("Mandibuzz", "Dark - Flying"))
            pokedex.add(Pokemon("Heatmor", "Fire"))
            pokedex.add(Pokemon("Durant", "Bug - Steel"))
            pokedex.add(Pokemon("Deino", "Dark - Dragon"))
            pokedex.add(Pokemon("Zweilous", "Dark - Dragon"))
            pokedex.add(Pokemon("Hydreigon", "Dark - Dragon"))
            pokedex.add(Pokemon("Larvesta", "Bug - Fire"))
            pokedex.add(Pokemon("Volcarona", "Bug - Fire"))
            pokedex.add(Pokemon("Cobalion", "Steel - Fighting"))
            pokedex.add(Pokemon("Terrakion", "Rock - Fighting"))
            pokedex.add(Pokemon("Virizion", "Grass - Fighting"))
            pokedex.add(Pokemon("Tornadus", "Flying"))
            pokedex.add(Pokemon("Thundurus", "Electric - Flying"))
            pokedex.add(Pokemon("Reshiram", "Dragon - Fire"))
            pokedex.add(Pokemon("Zekrom", "Dragon - Electric"))
            pokedex.add(Pokemon("Landorus", "Ground - Flying"))
            pokedex.add(Pokemon("Kyurem", "Dragon - Ice"))
            pokedex.add(Pokemon("Keldeo", "Water - Fighting"))
            pokedex.add(Pokemon("Meloetta", "Normal - Psychic"))
            pokedex.add(Pokemon("Genesect", "Bug - Steel"))
            pokedex.add(Pokemon("Chespin", "Grass"))
            pokedex.add(Pokemon("Quilladin", "Grass"))
            pokedex.add(Pokemon("Chesnaught", "Grass - Fighting"))
            pokedex.add(Pokemon("Fennekin", "Fire"))
            pokedex.add(Pokemon("Braixen", "Fire"))
            pokedex.add(Pokemon("Delphox", "Fire - Psychic"))
            pokedex.add(Pokemon("Froakie", "Water"))
            pokedex.add(Pokemon("Frogadier", "Water"))
            pokedex.add(Pokemon("Greninja", "Water - Dark"))
            pokedex.add(Pokemon("Bunnelby", "Normal"))
            pokedex.add(Pokemon("Diggersby", "Normal - Ground"))
            pokedex.add(Pokemon("Fletchling", "Normal - Flying"))
            pokedex.add(Pokemon("Fletchinder", "Fire - Flying"))
            pokedex.add(Pokemon("Talonflame", "Fire - Flying"))
            pokedex.add(Pokemon("Scatterbug", "Bug"))
            pokedex.add(Pokemon("Spewpa", "Bug"))
            pokedex.add(Pokemon("Vivillon", "Bug - Flying"))
            pokedex.add(Pokemon("Litleo", "Fire - Normal"))
            pokedex.add(Pokemon("Pyroar", "Fire - Normal"))
            pokedex.add(Pokemon("Flabébé", "Fairy"))
            pokedex.add(Pokemon("Floette", "Fairy"))
            pokedex.add(Pokemon("Florges", "Fairy"))
            pokedex.add(Pokemon("Skiddo", "Grass"))
            pokedex.add(Pokemon("Gogoat", "Grass"))
            pokedex.add(Pokemon("Pancham", "Fighting"))
            pokedex.add(Pokemon("Pangoro", "Fighting - Dark"))
            pokedex.add(Pokemon("Furfrou", "Normal"))
            pokedex.add(Pokemon("Espurr", "Psychic"))
            pokedex.add(Pokemon("Meowstic", "Psychic"))
            pokedex.add(Pokemon("Honedge", "Steel - Ghost"))
            pokedex.add(Pokemon("Doublade", "Steel - Ghost"))
            pokedex.add(Pokemon("Aegislash", "Steel - Ghost"))
            pokedex.add(Pokemon("Spritzee", "Fairy"))
            pokedex.add(Pokemon("Aromatisse", "Fairy"))
            pokedex.add(Pokemon("Swirlix", "Fairy"))
            pokedex.add(Pokemon("Slurpuff", "Fairy"))
            pokedex.add(Pokemon("Inkay", "Dark - Psychic"))
            pokedex.add(Pokemon("Malamar", "Dark - Psychic"))
            pokedex.add(Pokemon("Binacle", "Rock - Water"))
            pokedex.add(Pokemon("Barbaracle", "Rock - Water"))
            pokedex.add(Pokemon("Skrelp", "Poison - Water"))
            pokedex.add(Pokemon("Dragalge", "Poison - Dragon"))
            pokedex.add(Pokemon("Clauncher", "Water"))
            pokedex.add(Pokemon("Clawitzer", "Water"))
            pokedex.add(Pokemon("Helioptile", "Electric - Normal"))
            pokedex.add(Pokemon("Heliolisk", "Electric - Normal"))
            pokedex.add(Pokemon("Tyrunt", "Rock - Dragon"))
            pokedex.add(Pokemon("Tyrantrum", "Rock - Dragon"))
            pokedex.add(Pokemon("Amaura", "Rock - Ice"))
            pokedex.add(Pokemon("Aurorus", "Rock - Ice"))
            pokedex.add(Pokemon("Sylveon", "Fairy"))
            pokedex.add(Pokemon("Hawlucha", "Fighting - Flying"))
            pokedex.add(Pokemon("Dedenne", "Electric - Fairy"))
            pokedex.add(Pokemon("Carbink", "Rock - Fairy"))
            pokedex.add(Pokemon("Goomy", "Dragon"))
            pokedex.add(Pokemon("Sliggoo", "Dragon"))
            pokedex.add(Pokemon("Goodra", "Dragon"))
            pokedex.add(Pokemon("Klefki", "Steel - Fairy"))
            pokedex.add(Pokemon("Phantump", "Ghost - Grass"))
            pokedex.add(Pokemon("Trevenant", "Ghost - Grass"))
            pokedex.add(Pokemon("Pumpkaboo", "Ghost - Grass"))
            pokedex.add(Pokemon("Gourgeist", "Ghost - Grass"))
            pokedex.add(Pokemon("Bergmite", "Ice"))
            pokedex.add(Pokemon("Avalugg", "Ice"))
            pokedex.add(Pokemon("Noibat", "Flying - Dragon"))
            pokedex.add(Pokemon("Noivern", "Flying - Dragon"))
            pokedex.add(Pokemon("Xerneas", "Fairy"))
            pokedex.add(Pokemon("Yveltal", "Dark - Flying"))
            pokedex.add(Pokemon("Zygarde", "Dragon - Ground"))
            pokedex.add(Pokemon("Diancie", "Rock - Fairy"))
            pokedex.add(Pokemon("Hoopa", "Psychic - Ghost"))
            pokedex.add(Pokemon("Volcanion", "Fire - Water"))
            pokedex.add(Pokemon("Rowlet", "Grass - Flying"))
            pokedex.add(Pokemon("Dartrix", "Grass - Flying"))
            pokedex.add(Pokemon("Decidueye", "Grass - Ghost"))
            pokedex.add(Pokemon("Litten", "Fire"))
            pokedex.add(Pokemon("Torracat", "Fire"))
            pokedex.add(Pokemon("Incineroar", "Fire - Dark"))
            pokedex.add(Pokemon("Popplio", "Water"))
            pokedex.add(Pokemon("Brionne", "Water"))
            pokedex.add(Pokemon("Primarina", "Water - Fairy"))
            pokedex.add(Pokemon("Pikipek", "Normal - Flying"))
            pokedex.add(Pokemon("Trumbeak", "Normal - Flying"))
            pokedex.add(Pokemon("Toucannon", "Normal - Flying"))
            pokedex.add(Pokemon("Yungoos", "Normal"))
            pokedex.add(Pokemon("Gumshoos", "Normal"))
            pokedex.add(Pokemon("Grubbin", "Bug"))
            pokedex.add(Pokemon("Charjabug", "Bug - Electric"))
            pokedex.add(Pokemon("Vikavolt", "Bug - Electric"))
            pokedex.add(Pokemon("Crabrawler", "Fighting"))
            pokedex.add(Pokemon("Crabominable", "Fighting - Ice"))
            pokedex.add(Pokemon("Oricorio", "Fire - Flying"))
            pokedex.add(Pokemon("Cutiefly", "Bug - Fairy"))
            pokedex.add(Pokemon("Ribombee", "Bug - Fairy"))
            pokedex.add(Pokemon("Rockruff", "Rock"))
            pokedex.add(Pokemon("Lycanroc", "Rock"))
            pokedex.add(Pokemon("Wishiwashi", "Water"))
            pokedex.add(Pokemon("Mareanie", "Poison - Water"))
            pokedex.add(Pokemon("Toxapex", "Poison - Water"))
            pokedex.add(Pokemon("Mudbray", "Ground"))
            pokedex.add(Pokemon("Mudsdale", "Ground"))
            pokedex.add(Pokemon("Dewpider", "Water - Bug"))
            pokedex.add(Pokemon("Araquanid", "Water - Bug"))
            pokedex.add(Pokemon("Fomantis", "Grass"))
            pokedex.add(Pokemon("Lurantis", "Grass"))
            pokedex.add(Pokemon("Morelull", "Grass - Fairy"))
            pokedex.add(Pokemon("Shiinotic", "Grass - Fairy"))
            pokedex.add(Pokemon("Salandit", "Poison - Fire"))
            pokedex.add(Pokemon("Salazzle", "Poison - Fire"))
            pokedex.add(Pokemon("Stufful", "Normal - Fighting"))
            pokedex.add(Pokemon("Bewear", "Normal - Fighting"))
            pokedex.add(Pokemon("Bounsweet", "Grass"))
            pokedex.add(Pokemon("Steenee", "Grass"))
            pokedex.add(Pokemon("Tsareena", "Grass"))
            pokedex.add(Pokemon("Comfey", "Fairy"))
            pokedex.add(Pokemon("Oranguru", "Normal - Psychic"))
            pokedex.add(Pokemon("Passimian", "Fighting"))
            pokedex.add(Pokemon("Wimpod", "Bug - Water"))
            pokedex.add(Pokemon("Golisopod", "Bug - Water"))
            pokedex.add(Pokemon("Sandygast", "Ghost - Ground"))
            pokedex.add(Pokemon("Palossand", "Ghost - Ground"))
            pokedex.add(Pokemon("Pyukumuku", "Water"))
            pokedex.add(Pokemon("Type: Null", "Normal"))
            pokedex.add(Pokemon("Silvally", "Normal"))
            pokedex.add(Pokemon("Minior", "Rock - Flying"))
            pokedex.add(Pokemon("Komala", "Normal"))
            pokedex.add(Pokemon("Turtonator", "Fire - Dragon"))
            pokedex.add(Pokemon("Togedemaru", "Electric - Steel"))
            pokedex.add(Pokemon("Mimikyu", "Ghost - Fairy"))
            pokedex.add(Pokemon("Bruxish", "Water - Psychic"))
            pokedex.add(Pokemon("Drampa", "Normal - Dragon"))
            pokedex.add(Pokemon("Dhelmise", "Ghost - Grass"))
            pokedex.add(Pokemon("Jangmo-o", "Dragon"))
            pokedex.add(Pokemon("Hakamo-o", "Dragon - Fighting"))
            pokedex.add(Pokemon("Kommo-o", "Dragon - Fighting"))
            pokedex.add(Pokemon("Tapu Koko", "Electric - Fairy"))
            pokedex.add(Pokemon("Tapu Lele", "Psychic - Fairy"))
            pokedex.add(Pokemon("Tapu Bulu", "Grass - Fairy"))
            pokedex.add(Pokemon("Tapu Fini", "Water - Fairy"))
            pokedex.add(Pokemon("Cosmog", "Psychic"))
            pokedex.add(Pokemon("Cosmoem", "Psychic"))
            pokedex.add(Pokemon("Solgaleo", "Psychic - Steel"))
            pokedex.add(Pokemon("Lunala", "Psychic - Ghost"))
            pokedex.add(Pokemon("Nihilego", "Rock - Poison"))
            pokedex.add(Pokemon("Buzzwole", "Bug - Fighting"))
            pokedex.add(Pokemon("Pheromosa", "Bug - Fighting"))
            pokedex.add(Pokemon("Xurkitree", "Electric"))
            pokedex.add(Pokemon("Celesteela", "Steel - Flying"))
            pokedex.add(Pokemon("Kartana", "Grass - Steel"))
            pokedex.add(Pokemon("Guzzlord", "Dark - Dragon"))
            pokedex.add(Pokemon("Necrozma", "Psychic"))
            pokedex.add(Pokemon("Magearna", "Steel - Fairy"))
            pokedex.add(Pokemon("Marshadow", "Fighting - Ghost"))
            pokedex.add(Pokemon("Poipole", "Poison"))
            pokedex.add(Pokemon("Naganadel", "Poison - Dragon"))
            pokedex.add(Pokemon("Stakataka", "Rock - Steel"))
            pokedex.add(Pokemon("Blacephalon", "Fire - Ghost"))
            pokedex.add(Pokemon("Zeraora", "Electric"))
            pokedex.add(Pokemon("Meltan", "Steel"))
            pokedex.add(Pokemon("Melmetal", "Steel"))
            pokedex.add(Pokemon("Grookey", "Grass"))
            pokedex.add(Pokemon("Thwackey", "Grass"))
            pokedex.add(Pokemon("Rillaboom", "Grass"))
            pokedex.add(Pokemon("Scorbunny", "Fire"))
            pokedex.add(Pokemon("Raboot", "Fire"))
            pokedex.add(Pokemon("Cinderace", "Fire"))
            pokedex.add(Pokemon("Sobble", "Water"))
            pokedex.add(Pokemon("Drizzile", "Water"))
            pokedex.add(Pokemon("Inteleon", "Water"))
            pokedex.add(Pokemon("Skwovet", "Normal"))
            pokedex.add(Pokemon("Greedent", "Normal"))
            pokedex.add(Pokemon("Rookidee", "Flying"))
            pokedex.add(Pokemon("Corvisquire", "Flying"))
            pokedex.add(Pokemon("Corviknight", "Flying - Steel"))
            pokedex.add(Pokemon("Blipbug", "Bug"))
            pokedex.add(Pokemon("Dottler", "Bug - Psychic"))
            pokedex.add(Pokemon("Orbeetle", "Bug - Psychic"))
            pokedex.add(Pokemon("Nickit", "Dark"))
            pokedex.add(Pokemon("Thievul", "Dark"))
            pokedex.add(Pokemon("Gossifleur", "Grass"))
            pokedex.add(Pokemon("Eldegoss", "Grass"))
            pokedex.add(Pokemon("Wooloo", "Normal"))
            pokedex.add(Pokemon("Dubwool", "Normal"))
            pokedex.add(Pokemon("Chewtle", "Water"))
            pokedex.add(Pokemon("Drednaw", "Water - Rock"))
            pokedex.add(Pokemon("Yamper", "Electric"))
            pokedex.add(Pokemon("Boltund", "Electric"))
            pokedex.add(Pokemon("Rolycoly", "Rock"))
            pokedex.add(Pokemon("Carkol", "Rock - Fire"))
            pokedex.add(Pokemon("Coalossal", "Rock - Fire"))
            pokedex.add(Pokemon("Applin", "Grass - Dragon"))
            pokedex.add(Pokemon("Flapple", "Grass - Dragon"))
            pokedex.add(Pokemon("Appletun", "Grass - Dragon"))
            pokedex.add(Pokemon("Silicobra", "Ground"))
            pokedex.add(Pokemon("Sandaconda", "Ground"))
            pokedex.add(Pokemon("Cramorant", "Flying - Water"))
            pokedex.add(Pokemon("Arrokuda", "Water"))
            pokedex.add(Pokemon("Barraskewda", "Water"))
            pokedex.add(Pokemon("Toxel", "Electric - Poison"))
            pokedex.add(Pokemon("Toxtricity", "Electric - Poison"))
            pokedex.add(Pokemon("Sizzlipede", "Fire - Bug"))
            pokedex.add(Pokemon("Centiskorch", "Fire - Bug"))
            pokedex.add(Pokemon("Clobbopus", "Fighting"))
            pokedex.add(Pokemon("Grapploct", "Fighting"))
            pokedex.add(Pokemon("Sinistea", "Ghost"))
            pokedex.add(Pokemon("Polteageist", "Ghost"))
            pokedex.add(Pokemon("Hatenna", "Psychic"))
            pokedex.add(Pokemon("Hattrem", "Psychic"))
            pokedex.add(Pokemon("Hatterene", "Psychic - Fairy"))
            pokedex.add(Pokemon("Impidimp", "Dark - Fairy"))
            pokedex.add(Pokemon("Morgrem", "Dark - Fairy"))
            pokedex.add(Pokemon("Grimmsnarl", "Dark - Fairy"))
            pokedex.add(Pokemon("Obstagoon", "Dark - Normal"))
            pokedex.add(Pokemon("Perrserker", "Steel"))
            pokedex.add(Pokemon("Cursola", "Ghost"))
            pokedex.add(Pokemon("Sirfetch'd", "Fighting"))
            pokedex.add(Pokemon("Mr. Rime", "Ice - Psychic"))
            pokedex.add(Pokemon("Runerigus", "Ground - Ghost"))
            pokedex.add(Pokemon("Milcery", "Fairy"))
            pokedex.add(Pokemon("Alcremie", "Fairy"))
            pokedex.add(Pokemon("Falinks", "Fighting"))
            pokedex.add(Pokemon("Pincurchin", "Electric"))
            pokedex.add(Pokemon("Snom", "Ice - Bug"))
            pokedex.add(Pokemon("Frosmoth", "Ice - Bug"))
            pokedex.add(Pokemon("Stonjourner", "Rock"))
            pokedex.add(Pokemon("Eiscue", "Ice"))
            pokedex.add(Pokemon("Indeedee", "Psychic - Normal"))
            pokedex.add(Pokemon("Morpeko", "Electric - Dark"))
            pokedex.add(Pokemon("Cufant", "Steel"))
            pokedex.add(Pokemon("Copperajah", "Steel"))
            pokedex.add(Pokemon("Dracozolt", "Electric - Dragon"))
            pokedex.add(Pokemon("Arctozolt", "Electric - Ice"))
            pokedex.add(Pokemon("Dracovish", "Water - Dragon"))
            pokedex.add(Pokemon("Arctovish", "Water - Ice"))
            pokedex.add(Pokemon("Duraludon", "Steel - Dragon"))
            pokedex.add(Pokemon("Dreepy", "Dragon - Ghost"))
            pokedex.add(Pokemon("Drakloak", "Dragon - Ghost"))
            pokedex.add(Pokemon("Dragapult", "Dragon - Ghost"))
            pokedex.add(Pokemon("Zacian", "Fairy - Steel"))
            pokedex.add(Pokemon("Zamazenta", "Fighting - Steel"))
            pokedex.add(Pokemon("Eternatus", "Poison - Dragon"))
            pokedex.add(Pokemon("Kubfu", "Fighting"))
            pokedex.add(Pokemon("Urshifu", "Fighting - Dark"))
            pokedex.add(Pokemon("Zarude", "Dark - Grass"))
            pokedex.add(Pokemon("Regieleki", "Electric"))
            pokedex.add(Pokemon("Regidrago", "Dragon"))
            pokedex.add(Pokemon("Glastrier", "Ice"))
            pokedex.add(Pokemon("Spectrier", "Ghost"))
            pokedex.add(Pokemon("Calyrex", "Psychic - Grass"))

            return pokedex
        }
    }
}